import "./globals.css";
import SideNavigation from "../components/SideNavigation";
import TopNavigation from "@/components/TopNavigation";

export const metadata = {
  title: "Q-Tube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-900 text-zinc-200">
        <div className="h-screen flex flex-col">
          <TopNavigation />

          <div className="flex-1 flex">
            <SideNavigation />
            <main className="flex-1">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
